name: Build KeyDB
on:
  workflow_dispatch:
env:
  VERSION: "6.3.4"
  NAME: "keydb"
  
jobs:
  slackware-job:
    permissions: write-all
    runs-on: ubuntu-latest
    container: aclemons/slackrepo
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update and install packages
      run: |
        echo "================================= Updating packages ================================="
        CONF_FILE="/etc/slackpkg/slackpkg.conf"
        sed -i "s/^DIALOG=.*/DIALOG=off/" "$CONF_FILE"
        sed -i "s/^BATCH=.*/BATCH=on/" "$CONF_FILE"
        sed -i "s/^DEFAULT_ANSWER=.*/DEFAULT_ANSWER=y/" "$CONF_FILE"
        slackpkg update <<< y
        slackpkg install jemalloc
        wget https://slackers.it/repository/slackware64-current/hiredis/hiredis-1.2.0-x86_64-1cf.txz
        wget https://slackware.uk/people/alien/sbrepos/15.0/x86_64/lua/lua-5.1.5-x86_64-3alien.tgz
        installpkg *.txz
    - name: Build
      run: |
        echo "================================= Downloading source code ================================="
        git clone --depth 1 --branch v6.3.4 https://github.com/bobbintb/KeyDB.git
        cd KeyDB/
        git submodule init && git submodule update
        echo "================================= Building ================================="
        make USE_SYSTEMD=no USE_SYSTEM_HIREDIS=yes USE_SYSTEM_JEMALLOC=yes USE_SYSTEM_LUA=yes DEBUG=
