name: Build KeyDB autoslackpack
on:
  workflow_dispatch:
env:
  VERSION: "6.3.4"
  NAME: "keydb"
  
jobs:
  slackware-job:
    permissions: write-all
    runs-on: ubuntu-latest
    container: spaceinvaderone/auto_slack_pack
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update and install packages
      run: |
        echo "================================= Updating packages ================================="
        CONF_FILE="/etc/slackpkg/slackpkg.conf"
        sed -i "s/^DIALOG=.*/DIALOG=off/" "$CONF_FILE"
        sed -i "s/^BATCH=.*/BATCH=on/" "$CONF_FILE"
        sed -i "s/^DEFAULT_ANSWER=.*/DEFAULT_ANSWER=y/" "$CONF_FILE"
        slackpkg update <<< y
        slackpkg install jemalloc infozip
        wget https://slackers.it/repository/slackware64-current/hiredis/hiredis-1.2.0-x86_64-1cf.txz
        # wget https://slackers.it/repository/slackware64-current/luarocks/luarocks-3.11.1-x86_64-1cf.txz
        wget https://slackware.uk/people/alien/sbrepos/15.0/x86_64/lua/lua-5.1.5-x86_64-3alien.tgz
        installpkg *.tgz
        installpkg *.txz
        mkdir /usr/include/lua5.1
        ln /usr/include/lua.h /usr/include/lua5.1/lua.h
        ln /usr/include/lua.hpp /usr/include/lua5.1/lua.hpp
        ln /usr/include/luaconf.h /usr/include/lua5.1/luaconf.h
        ln /usr/include/lualib.h /usr/include/lua5.1/lualib.h
        # luarocks install luarocks
        # luarocks install luabitop
        # luarocks install struct
        # luarocks install lua-cmsgpack
    - name: Build
      run: |
        echo "================================= Downloading source code ================================="
        git clone --depth 1 --branch v6.3.4 https://github.com/bobbintb/KeyDB.git
        cd KeyDB/
        git submodule init && git submodule update
        cd src/
        rm Makefile
        wget https://raw.githubusercontent.com/bobbintb/KeyDB/refs/heads/main/src/Makefile
        # wget https://raw.githubusercontent.com/bobbintb/KeyDB/refs/heads/main/src/sdscompat.h
        cd ..
        # rm ./deps/hiredis/sdscompat.h
        # cp ./src/sdscompat.h /usr/include/hiredis/sdscompat.h
        echo "================================= Building ================================="
        # wget https://slackware.uk/slackware/slackware64-current/slackware64/n/openssl-3.3.2-x86_64-1.txz
        wget https://slackware.uk/people/alien/multilib/current/slackware64-compat32/n-compat32/openssl-compat32-3.3.1-x86_64-1compat32.txz
        installpkg openssl-compat32-3.3.1-x86_64-1compat32.txz
        rm openssl-compat32-3.3.1-x86_64-1compat32.txz
        make USE_SYSTEMD=no USE_SYSTEM_JEMALLOC=yes DEBUG=
