name: Build KeyDB rhel
on:
  workflow_dispatch:
env:
  VERSION: "6.3.4"
  NAME: "keydb"
  
jobs:
  slackware-job:
    permissions: write-all
    runs-on: ubuntu-latest
    container: redhat/ubi8
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update and install packages
      run: |
        echo "================================= Updating packages ================================="
        
